name: covidapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  google_fonts: ^0.3.9
  simple_animations: ^1.3.9
  flare_flutter: ^2.0.1
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  carousel_slider: ^1.4.1
  url_launcher: ^5.4.2
  geolocator: ^5.3.0
  workmanager: ^0.2.0
  location:
    git:
      url: git://github.com/Lyokone/flutterlocation.git
      ref: background_location




  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
